export const julyFood = [
  { name: 'aubergine', image: 's3://parsnip-hackathon/aubergine.svg' },
  { name: 'blackberry', image: 's3://parsnip-hackathon/blackberry.svg' },
  { name: 'blueberry', image: 's3://parsnip-hackathon/blueberry.svg' },
  { name: 'broccoli', image: 's3://parsnip-hackathon/broccoli.svg' },
  { name: 'carrot', image: 's3://parsnip-hackathon/carrot.svg' },
  { name: 'chard', image: 's3://parsnip-hackathon/chard.svg' },
  { name: 'garlic', image: 's3://parsnip-hackathon/garlic.svg' },
  { name: 'onion', image: 's3://parsnip-hackathon/onion.svg' },
  { name: 'pea', image: 's3://parsnip-hackathon/pea.svg' },
  { name: 'radish', image: 's3://parsnip-hackathon/radish.svg' },
  { name: 'strawberry', image: 's3://parsnip-hackathon/strawberry.svg' },
  { name: 'summer-squash', image: 's3://parsnip-hackathon/summer-squash.svg' },
  { name: 'turnip', image: 's3://parsnip-hackathon/turnip.svg' },
];
